# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-01 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributeAPP', '0002_auto_20200430_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ques_upload', models.ImageField(upload_to='questionIMG/%Y/%m/%d/')),
                ('option1', models.CharField(max_length=300)),
                ('option2', models.CharField(max_length=300)),
                ('option3', models.CharField(max_length=300)),
                ('option4', models.CharField(max_length=300)),
                ('correct_option', models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3'), ('D', '4')], max_length=1)),
                ('solution', models.TextField()),
                ('sol_upload', models.ImageField(upload_to='solutionIMG/%Y/%m/%d/')),
                ('level_of_ques', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('about_question', models.CharField(max_length=300)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributeAPP.SubjectTopic')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
