# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributeAPP', '0004_auto_20200501_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestion',
            name='ques_upload',
            field=models.ImageField(upload_to='contributeAPP/static/questionIMG/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='sol_upload',
            field=models.ImageField(upload_to='contributeAPP/static/solutionIMG/%Y/%m/%d/'),
        ),
    ]
