# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-02 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributeAPP', '0006_auto_20200501_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestion',
            name='ques_upload',
            field=models.ImageField(upload_to='questionIMG/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='sol_upload',
            field=models.ImageField(upload_to='solutionIMG/%Y/%m/%d/'),
        ),
    ]
