# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-02 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributeAPP', '0009_auto_20200502_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestion',
            name='about_question',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
